### ISSUE TITLE
method names

### ISSUE THREAD

**Issue by Chris7** [wooey/clinto#1]
What should the core method be? I think import ArgParseNodeBuilder is a bit verbose (and assumes ArgParse).

how about:

from clinto import schema

initialize with: schema(script_name, script_path)

The user can naturally iterate over that, as well as call functions like getJSON and other intermediates.

**Comment by mfitzp** [comment]
How about Parser? Since it's the class you call to do the parsing and then dump the result. Schema is also fine but sounds a bit like it's XML something or other.

Since it's a class name it should be capitalised, right?

**Comment by Chris7** [comment]
from clinto import Parser

parser = Parser(....).
parser.xxx

I think it works nicely, will move it over shortly.
