### ISSUE TITLE
Import zip script error : UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 54

### ISSUE THREAD

**Issue by pymenow** [wooey/clinto#34]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 54: character maps to <undefined>

This is with 0.10 Wooey 

Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/wooey/script/add/
1.11.13
ParserError
Traceback (most recent call last):   File "C:\Users\cheta\Anaconda3\lib\site-packages\clinto\parsers\argparse_.py", line 252, in extract_parser     ast_source = source_parser.parse_source_file(self.script_path)   File "C:\Users\cheta\Anaconda3\lib\site-packages\clinto\ast\source_parser.py", line 39, in parse_source_file     s = f.read()   File "C:\Users\cheta\Anaconda3\lib\encodings\cp1252.py", line 23, in decode     return codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 54: character maps to <undefined>
C:\Users\cheta\Anaconda3\lib\site-packages\wooey\signals.py in script_version_postsave, line 64
C:\Users\cheta\Anaconda3\python.exe
3.6.3
['D:\\AUTOREPORT',  'C:\\Users\\cheta\\Anaconda3\\python36.zip',  'C:\\Users\\cheta\\Anaconda3\\DLLs',  'C:\\Users\\cheta\\Anaconda3\\lib',  'C:\\Users\\cheta\\Anaconda3',  'C:\\Users\\cheta\\Anaconda3\\lib\\site-packages',  'C:\\Users\\cheta\\Anaconda3\\lib\\site-packages\\Babel-2.5.0-py3.6.egg',  'C:\\Users\\cheta\\Anaconda3\\lib\\site-packages\\win32',  'C:\\Users\\cheta\\Anaconda3\\lib\\site-packages\\win32\\lib',  'C:\\Users\\cheta\\Anaconda3\\lib\\site-packages\\Pythonwin',  'D:\\AUTOREPORT']
Tue, 5 Jun 2018 23:05:37 +0000

**Comment by Chris7** [comment]
Can you post the script and `pip freeze`?

**Comment by pymenow** [comment]
Here is the pip freeze  : 

alabaster==0.7.10
amqp==2.3.2
anaconda-client==1.6.14
anaconda-navigator==1.8.7
anaconda-project==0.8.2
anyjson==0.3.3
apipkg==1.4
argon2-cffi==18.1.0
asn1crypto==0.24.0
astroid==1.6.3
astropy==3.0.2
attrs==18.1.0
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
billiard==3.5.0.3
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.3
bokeh==0.12.16
boto==2.48.0
Bottleneck==1.2.1
celery==4.1.1
certifi==2018.4.16
cffi==1.11.5
Chameleon==3.2
chardet==3.0.4
check-manifest==0.37
click==6.7
clinto==0.2.1
cloudpickle==0.5.3
clyent==1.2.2
cmarkgfm==0.4.2
colorama==0.3.9
conda==4.5.4
conda-build==3.10.7
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.2.2
cycler==0.10.0
Cython==0.28.2
cytoolz==0.9.0.1
dask==0.17.5
datashape==0.5.4
decorator==4.3.0
defusedxml==0.5.0
devpi-client==4.0.1
devpi-common==3.2.2
devpi-server==4.4.0
devpi-web==3.2.2
distributed==1.21.8
Django==1.9.13
django-autoslug==1.9.3
django-celery==3.2.2
django-celery-results==1.0.1
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
execnet==1.5.0
fastcache==1.0.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
future==0.16.0
gevent==1.3.0
glob2==0.6
gmpy2==2.0.8
greenlet==0.4.13
h5py==2.7.1
heapdict==1.0.0
honcho==1.0.1
html5lib==1.0.1
hupper==1.2
idna==2.6
imageio==2.3.0
imagesize==1.0.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
jsonfield==2.0.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
kiwisolver==1.0.1
kombu==4.2.1
lazy-object-proxy==1.3.1
llvmlite==0.23.1
locket==0.2.0
lxml==4.2.1
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.0
mkl-random==1.0.1
more-itertools==4.1.0
mpmath==1.0.0
msgpack==0.5.6
msgpack-python==0.5.6
multipledispatch==0.5.0
navigator-updater==0.2.1
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numba==0.38.0
numexpr==2.6.5
numpy==1.14.3
numpydoc==0.8.0
odo==0.5.1
olefile==0.45.1
openpyxl==2.5.3
packaging==17.1
pandas==0.23.0
pandocfilters==1.4.2
parso==0.2.0
partd==0.3.8
passlib==1.7.1
PasteDeploy==1.5.2
path.py==11.0.1
pathlib2==2.3.2
patsy==0.5.0
PeakUtils==1.1.0
pep8==1.7.1
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.1.0
pkginfo==1.4.2
plaster==1.0
plaster-pastedeploy==0.5
plotly==2.7.0
pluggy==0.6.0
ply==3.11
prompt-toolkit==1.0.15
psutil==5.4.5
ptyprocess==0.5.2
py==1.5.3
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.8.4
pyodbc==4.0.23
pyOpenSSL==18.0.0
pyparsing==2.2.0
pyramid==1.9.2
pyramid-chameleon==0.3
PySocks==1.6.8
pytest==3.5.1
pytest-arraydiff==0.2
pytest-astropy==0.3.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
pytz==2018.4
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
readme-renderer==20.0
repoze.lru==0.7
requests==2.18.4
rope==0.10.7
ruamel-yaml==0.15.35
scapy==2.4.0
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.1.0
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.2.7
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.3
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==5.0.2
tox==3.0.0
tqdm==4.19.5
traitlets==4.3.2
translationstring==1.3
typing==3.6.4
unicodecsv==0.14.1
urllib3==1.22
venusian==1.1.0
vine==1.1.4
virtualenv==15.2.0
waitress==1.1.0
wcwidth==0.1.7
webencodings==0.5.1
WebOb==1.8.1
Werkzeug==0.14.1
Whoosh==2.7.4
widgetsnbextension==3.2.1
wooey==0.10.0
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.4
xlwt==1.3.0
zict==0.1.3
zope.deprecation==4.3.0
zope.interface==4.5.0

**Comment by Chris7** [comment]
Thanks for that, could you post the script as well? That is probably the most important part. If it's private, you could email it to me as well.

**Comment by pymenow** [comment]
@Chris7  I have emailed the script to you, thank you !
