### ISSUE TITLE
zip support broken with v.12 wooey

### ISSUE THREAD

**Issue by pymenow** [wooey/clinto#39]
I get the below error importing a zip file, works fine with 0.10

Request Method: | POST
-- | --
http://testnnnnnn.com/admin/wooey/script/add/
3.0.5
ParserError
Traceback (most recent call last):   File "/usr/local/lib/python3.7/site-packages/clinto/parsers/argparse_.py", line 253, in extract_parser     ast_source = source_parser.parse_source_file(self.script_path)   File "/usr/local/lib/python3.7/site-packages/clinto/ast/source_parser.py", line 39, in parse_source_file     s = f.read()   File "/usr/local/lib/python3.7/codecs.py", line 322, in decode     (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 14: invalid continuation byte
/wooey_build/wooey/signals.py in script_version_postsave, line 64
/usr/local/bin/python
3.7.7
['/docker_wooey',  '/docker_wooey',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages',  '/wooey_build']
Wed, 29 Apr 2020 18:02:21 +0000

**Comment by Chris7** [comment]
Could you attach or email me the zip?

**Comment by pymenow** [comment]
Thanks @Chris7 Ive emailed you the zip

**Comment by muhammadvellani** [comment]
it seems to be not working for me as well. @Chris7

**Comment by pymenow** [comment]
> Could you attach or email me the zip?

Chris just checking if you received the zip file .

**Comment by Chris7** [comment]
Hey, I have but have been unable to delve into the root cause (bit swamped with work atm -- in the life sciences and we're doing some covid19 things). This is the test asset for zip parsing:

https://github.com/wooey/clinto/blob/345b5dd0052e8dddf6689f5b6ef087f20993afd9/clinto/tests/test_parsers.py#L156

I took a quick look at it and there is an error around a null byte within the source code, but another guess is around the system encoding.

**Comment by Chris7** [comment]
Ok, it looks like a bad error message, but the root problem is the modules don't exist at import time on the webserver. I'm getting a bad import on numpy. I made a PR with some better error messages t omake this easier to detect in the future, but will need to polish it before I merge it in. Can you verify?

**Comment by pymenow** [comment]
Hello @Chris7 i installed the dependencies including numpy  into the docker image and checked I still get the same error.

**Comment by Chris7** [comment]
Are you installing with `pip` or `pip3`? Docker Wooey is setup with python3. Also, could you try this with the latest clinto branch?

`pip3 install --force-reinstall git+git://github.com/wooey/clinto@update-parser-errors`

**Comment by pymenow** [comment]
Oops ! Been using pip to update the wooey images . Will change to pip3 as well as try the above patch .

**Comment by pymenow** [comment]
To test this I only installed on a fresh image build with no other changes.

pip3 install --force-reinstall git+git://github.com/wooey/clinto@update-parser-errors

And now I see the error.

Technique: try-catch
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/clinto/parsers/argparse_.py", line 300, in extract_parser
    "__file__": self.script_path,
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'numpy'

**Comment by Chris7** [comment]
New version being released soonish will have the better error reporting. Thanks for testing!
