### ISSUE TITLE
Try / Except for Python 3 fails

### ISSUE THREAD

**Issue by mfitzp** [wooey/clinto#8]
Scripts using `try...except` blocks to conditionally import for Python 3 fail as the `try...except` block is collapsed during the parsing process.

**Comment by Chris7** [comment]
Good point, we can flip the logic around to make it work (define python2 xrange as six.range, so we have a safe fallback without having to trudge through the AST swamp)

**Comment by Chris7** [comment]
Bah, I completely misinterpretted this. OK, we do have to enter that swamp.

**Comment by mfitzp** [comment]
I was wondering actually whether there might be a way to do a completely dumb fallback where we just find the line containing `parser.parse_args()` crop the file to there and exec it.

The AST stuff is just to prevent scripts that can run with no parameters from executing completely. The above would do that, in a blunt sort of way.

**Comment by mfitzp** [comment]
See https://github.com/wooey/clinto/pull/9 for a workaround.

**Comment by mfitzp** [comment]
@Chris7 I think we can close this now we have the monkey-patching approach in. We might be able to completely remove the AST approach (although perhaps there are other command line methods where we'll need it again?)

**Comment by Chris7** [comment]
I can't remember the exact example, but i recently encountered a situation that the AST was necessary so i say keep it.

**Comment by Chris7** [comment]
But I think we can close this.
